app/views/__init__.py
from flask import Blueprint, render_template, url_for, redirect, request, make_response, send_from_directory, jsonify
from flask_login import current_user
from ..extensions import login_required
from flask_babel import gettext

from .users import app as users_view
from .sensors import app as sensors_view
from .monitors import app as monitors_view
from .api import app as api_view
from ..models import Sensor, SearchForm
import json

app = Blueprint('main', __name__)
app.register_blueprint(users_view, url_prefix='')
app.register_blueprint(sensors_view, url_prefix='')
app.register_blueprint(monitors_view, url_prefix='')
app.register_blueprint(api_view, url_prefix='')

@app.route('/')
def index():
    return redirect(url_for('.map'))

@app.route('/map', methods=['GET'])
@login_required
def map():
    sensors = Sensor.query.all()
    sens = []
    center_lat = request.args.get('lat')
    center_lon = request.args.get('lon')
    center = []
    if (center_lat and center_lon):
        center = [center_lat, center_lon]
    for sensor in sensors:
        sens.append(sensor)
    
    return render_template('pages/map.html.j2', sensors=sens, center=center, navbar_highlight_map=True)
    

@app.route('/serviceworker.js')
def service_worker():
    response = make_response(send_from_directory('static/js/','serviceworker.js'))
    response.headers['Content-Type'] = 'application/javascript'
    response.headers['Service-Worker-Allowed'] = '/'
    return response

# (A2) FLASK SETTINGS + INIT - CHANGE TO YOUR OWN!
VAPID_SUBJECT = "mailto:your@email.com"
VAPID_PRIVATE = "YOUR-PRIVATE-KEY"

# (B3) PUSH DEMO
@app.route("/subscribe", methods=["POST"])
@login_required
def push():
    # (B3-1) GET SUBSCRIBER
    sub = json.loads(request.form["sub"])
    current_user.new_subscription(sub)
    return 'OK'

app/templates/includes/background.html.j2
<div class="-z-50 fixed top-0 w-full h-full overflow-hidden bg-blue-200">

  <div class="-z-10 fixed bottom-0 w-full h-[6%] bg-[#f6f6f6]"></div>
  <img class="-z-10 fixed bottom-[5%] w-full animate-wave1 print:hidden"
       src="{{ url_for('static', filename='background_images/wave1.svg') }}"
       alt="Background image 1"/>

  <div class="-z-20 fixed bottom-[5%] w-full h-[16%] bg-[#d6e4f0]"></div>
  <img class="-z-20 fixed bottom-[20%] w-full animate-wave2 print:hidden"
       src="{{ url_for('static', filename='background_images/wave2.svg') }}"
       alt="Background image 2"/>

  <div class="-z-30 fixed bottom-[20%] w-full h-[26%] bg-[#1e56a0]"></div>
  <img class="-z-30 fixed bottom-[45%] w-full animate-wave3 print:hidden"
       src="{{ url_for('static', filename='background_images/wave3.svg') }}"
       alt="Background image 3"/>

  <div class="-z-40 fixed bottom-[45%] w-full h-[21%] bg-[#163172]"></div>
  <img class="-z-40 fixed bottom-[65%] w-full animate-wave4 print:hidden"
       src="{{ url_for('static', filename='background_images/wave4.svg') }}"
       alt="Background image 4"/>

</div>

app/templates/includes/footer.html.j2
<footer class="relative justify-between items-center p-0 flex min-h-[12%]">
  <span>
    <span>
      &copy; 2023 <a href="#">iTIC</a>. {{ _('All Rights Reserved') }}.
    </span>
    <ul>
      <li>
        <a href="#">{{ _('About') }}</a>
      </li>
      <li>
        <a href="#">{{ _('Privacy Policy') }}</a>
      </li>
      <li>
        <a href="#">{{ _('Contact') }}</a>
      </li>
    </ul>
  </span>
</footer>

app/templates/includes/head.html.j2
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">

  {# <script src="https://cdn.tailwindcss.com"></script> #}
  <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
  
  {# Flowbite (for navbar) #}
  <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}">
  <script src="{{ url_for('static', filename='js/serviceworker_register.js') }}"></script>

  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
  <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>

  {% if title %}
    <title>{{ title }} | HydroLab</title>
  {% else %}
    <title>HydroLab</title>
  {% endif %}
</head>

app/templates/includes/navbar.html.j2
{% set current_item_classes = 'class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0" aria-current="page"' %}
{% set other_item_classes = 'class="block py-2 pl-3 pr-4 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0"' %}

<header class="bg-white relative p-0">
<nav class="bg-white border-gray-200 w-full">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="/" class="flex items-center">
        <img src="{{ url_for('static', filename='navlab_logo.svg') }}" class="h-12 mr-3" alt="HydroLab Logo" />
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">{{ _('Open main menu') }}</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white">
        <li>
          <a href="{{ url_for('main.map') }}" {{ current_item_classes if navbar_highlight_map else other_item_classes }}>{{ _('Map') }}</a>
        </li>
        <li>
          <a href="{{ url_for('main.sensors.sensors') }}" {{ current_item_classes if navbar_highlight_sensors else other_item_classes }}>{{ _('Sensors') }}</a>
        </li>
        <li>
          <a href="{{ url_for('main.monitors.monitoring') }}" {{ current_item_classes if navbar_highlight_monitoring else other_item_classes }}>{{ _('Monitoring') }}</a>
        </li>
        <li>
          <a href="{{ url_for('main.users.profile') }}" {{ current_item_classes if navbar_highlight_profile else other_item_classes }}>{{ _('Profile') }}</a>
        </li>
        {% if current_user.permit(3) %}
        <li>
          <a href="{{ url_for('main.users.users') }}" {{ current_item_classes if navbar_highlight_users else other_item_classes }}>{{ _('Users') }}</a>
        </li>
        {% endif %}
        <li>
          <a href="{{ url_for('main.users.logout') }}" {{ current_item_classes if navbar_highlight_logout else other_item_classes }}>{{ _('Log Out') }}</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</header>

app/templates/includes/title.html.j2
{% if request.args.get('search') is none %}
  {% set search_query = '' %}
{% else %}
  {% set search_query = request.args.get('search') %}
{% endif %}

<div
  class="bg-white bg-opacity-90 max-w-[1250px] mx-auto border-black border rounded p-4 flex flex-wrap items-center mb-7 justify-between">
  <form id="search_form" method="get" action="">
    <h1 class="text-blue-900 font-bold mr-4 text-2xl text-center leading-relaxed">{{ h1_text }}
      {% if not search_form_hide %}
        {{ search_form.search(class_="text-black font-medium rounded-lg text-sm pl-5 py-1.5 border-gray border
        placeholder:text-gray h-full", value_=search_query) }}
        <button type="submit" class="scale-[65%] ml-[-0.7em] px-2 pb-1 rounded hover:bg-gray-200">
          <i class="fa fa-sm fa-search"></i>
        </button>
      {% endif %}
    </h1>
  </form>
  {% if not left_button_hide %}
    <a href="{{ left_button_url }}" class="xm:mx-auto xm:py-1.5">
      <button type="button"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-1.5">{{ left_button_text }}</button>
    </a>
  {% endif %}
</div>